### PR TITLE
schema created, models genned

### PR DESCRIPTION
**Pull request by shaybrow**

### CODE REVIEW

**Review by wordhou — COMMENTED** [review]
Looks great!

**Review by wordhou — APPROVED** [review]
Looks great!

**Comment by PotatoGod123** [comment]
> 
> 
> Looks great!

Awesome!

**Comment by wordhou** [comment]
Did you run `amplify push` before committing changes? I'm getting 11 modified files after running `amplify pull`.

        modified:   amplify/backend/api/trueproofAPI/parameters.json
        modified:   amplify/backend/api/trueproofAPI/resolvers/README.md
        modified:   amplify/backend/api/trueproofAPI/schema.graphql
        modified:   amplify/backend/api/trueproofAPI/stacks/CustomResources.json
        modified:   amplify/backend/api/trueproofAPI/transform.conf.json
        modified:   amplify/backend/auth/trueproof228d7488/parameters.json
        modified:   amplify/backend/auth/trueproof228d7488/trueproof228d7488-cloudformation-template.yml
        modified:   amplify/backend/backend-config.json
        modified:   amplify/backend/tags.json
        modified:   amplify/cli.json
        modified:   app/src/main/java/com/amplifyframework/datastore/generated/model/Batch.java

**Pull request merged**
